### PR TITLE
detect OpenFOAM dev version

### LINKED ISSUE #19: init fails when OpenFOAM version is dev
When OpenFOAM's version is `dev`, this module fails. Here's a traceback:
```
Log: Traceback (most recent call last):
  File "<string>", line 120, in InitApplications
  File "<string>", line 116, in <module>
  File "<string>", line 41, in __init__
  File "/home/sergey/.FreeCAD/Mod/Cfd/cfdguiobjects/CfdPreferencePage.py", line
 41, in <module>
    import CfdFoamTools
  File "/home/sergey/.FreeCAD/Mod/Cfd/CfdFoamTools.py", line 58, in <module>
    import FoamCaseBuilder  # this should not be imported in other py file: cas
e writer
  File "/home/sergey/.FreeCAD/Mod/Cfd/FoamCaseBuilder/__init__.py", line 27, in
 <module>
    from .config import *
  File "/home/sergey/.FreeCAD/Mod/Cfd/FoamCaseBuilder/config.py", line 125, in
<module>
    _detectedFoamVersion = _detectFoamVersion()
  File "/home/sergey/.FreeCAD/Mod/Cfd/FoamCaseBuilder/config.py", line 89, in _
detectFoamVersion
    _version = tuple([int(foam_ver), 0])  # version 7 has no minor version
ValueError: invalid literal for int() with base 10: 'dev'
```

### PR DESCRIPTION
**Pull request by matsievskiysv**
Detect OpenFOAM `dev` version

Closes #19

### CODE REVIEW

**Comment by qingfengxia** [comment]
The latest OpenFOAM is 8.x,   can we set a really big number to indicate it is latest.

Secondly,  ubuntu 's openfoam use a version of 19.06, seems change the origin of source code.

**Comment by matsievskiysv** [comment]
> do you happen to know any command to detect openfoam?

Do you mean detect foam version or location?

**Comment by qingfengxia** [comment]
I had a requirement to detect OpenFOAM installation into WSL, to let  CFD  on windows working with official openfoam. 
It once works,now breaks.  I am looking for a exe like "foamVersion"

**Comment by matsievskiysv** [comment]
`WM_PROJECT_VERSION` envvar seems to be the only method.

**Comment by matsievskiysv** [comment]
BTW, this code is unnecessarily complicated. Python can access environment variables:

```python
from os import environ

path = environ.get("WM_PROJECT_DIR", None)
version = environ.get("WM_PROJECT_VERSION", None)
if not version or not path:
    raise RuntimeError("OpenFOAM envvars are not set")

```

**Comment by qingfengxia** [comment]
`from os import environ

path = environ.get("WM_PROJECT_DIR", None)
version = environ.get("WM_PROJECT_VERSION", None)
if not version or not path:
    raise RuntimeError("OpenFOAM envvars are not set")
`
will only work if FreeCAD is running from linux terminal.  It will not work if FreeCAD is started from start manual even for Linux.   because  all those env var are yet source to bash. 

I have updated config.py yesterday.

**Comment by matsievskiysv** [comment]
> I have updated config.py yesterday

I don't see this update

**Pull request closed without merging**
